export  class  Auto_item1{
  name:string='';
  status:boolean=false;
}
 const autoItems: Auto_item1[] = [
  { name: 'light', status: true },
  { name: 'chair', status: true },
  { name: 'rain', status: true }
];
 const autoItems1: Auto_item1[]=[
   { name: 'rest', status: true },
   { name: 'light', status: true },
   { name: 'ele', status: true },
   { name: 'oil',status: true}
 ];
export class EmergencyContact {
  name: string = ''
  phone: string = ''
}
